//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHUE.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSHUE.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is João but you can call me John. I&apos;m 21 and I live in Rio Claro, São Paulo, Brazil. Currently studing Computer Science in Universidade Estadual Paulista (UNESP). For now I do internship for an IT company. C#, XAML and C are the languages I like the most, I moved recently from the good old WinForms to WPF and I&apos;m loving the greater variety of things you can do with it. I didn&apos;t want to use UWP because there&apos;s still a lot of people using Windows 7, but I tried to make the UI as good as in UWP. I got  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So that CSHUE can know what is going on in your CS:GO, a specific .cfg file must exist in the game&apos;s cfg folder, a gamestate_integration_cshue.cfg.
        ///
        ///If the bellow button is pressed, CSHUE will automatically try to find where CS:GO is installed in your machine, creating then the required file. Doesn&apos;t matter where you installed it, my precious application is going to find it MUAHAHA... Ahem... Here&apos;s the button:.
        /// </summary>
        public static string ConfigText {
            get {
                return ResourceManager.GetString("ConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .cfg.
        /// </summary>
        public static string CreateCfg {
            get {
                return ResourceManager.GetString("CreateCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO GSI.
        /// </summary>
        public static string CSGOGSI {
            get {
                return ResourceManager.GetString("CSGOGSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateButton {
            get {
                return ResourceManager.GetString("DonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t expect much finantial return from this application, but who knows, right? Donations are always appreciated.
        ///
        ///I&apos;m linking to a PayPal donation page. You will be able to donate from 1 to 9,999,999.99 dolars, any higher than this, please, email me a time and place and we meet there. You will also be able to choose &quot;Make this a monthly donation&quot; if you want to, well, make this a monthly donation..
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        public static string DonationCountry {
            get {
                return ResourceManager.GetString("DonationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string DonationCurrency {
            get {
                return ResourceManager.GetString("DonationCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSHUE%20donation.
        /// </summary>
        public static string DonationDescription {
            get {
                return ResourceManager.GetString("DonationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the above url in a browser.
        ///The url is composed of:
        ///	my PayPal email: joao7yt@gmail.com
        ///	a purpose description: CSHUE Donation
        ///	a country code: US
        ///	a currency code: USD.
        /// </summary>
        public static string DonationDetails {
            get {
                return ResourceManager.GetString("DonationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;
        ///business=joao7yt@gmail.com&amp;lc=US&amp;
        ///item_name=CSHUE%20Donation&amp;currency_code=USD&amp;
        ///bn=PP%2dDonationsBF.
        /// </summary>
        public static string DonationLink {
            get {
                return ResourceManager.GetString("DonationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File created at.
        /// </summary>
        public static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me.
        /// </summary>
        public static string FollowMe {
            get {
                return ResourceManager.GetString("FollowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find CS:GO path..
        /// </summary>
        public static string WarningCSGO {
            get {
                return ResourceManager.GetString("WarningCSGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find CS:GO Game State Integration file..
        /// </summary>
        public static string WarningGSI {
            get {
                return ResourceManager.GetString("WarningGSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO Game State Integration file is corrupted..
        /// </summary>
        public static string WarningGSICorrupted {
            get {
                return ResourceManager.GetString("WarningGSICorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Steam path..
        /// </summary>
        public static string WarningSteam {
            get {
                return ResourceManager.GetString("WarningSteam", resourceCulture);
            }
        }
    }
}
