//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHUE.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSHUE.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is João but you can call me John. I&apos;m 21 and I live in Rio Claro, São Paulo, Brazil. Currently studing Computer Science in Universidade Estadual Paulista (UNESP). For now I do internship for an IT company. C#, XAML and C are the languages I like the most, I moved recently from the good old WinForms to WPF and I&apos;m loving the greater variety of things you can do with it. I didn&apos;t want to use UWP because there&apos;s still a lot of people using Windows 7, but I tried to make the UI as good as in UWP. I got  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all the settings to default?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically activate between.
        /// </summary>
        public static string AutomaticallyActivate {
            get {
                return ResourceManager.GetString("AutomaticallyActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically deactivate if not in the above range.
        /// </summary>
        public static string AutomaticallyDeactivate {
            get {
                return ResourceManager.GetString("AutomaticallyDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb Blink.
        /// </summary>
        public static string BombBlink {
            get {
                return ResourceManager.GetString("BombBlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb Explodes.
        /// </summary>
        public static string BombExplodes {
            get {
                return ResourceManager.GetString("BombExplodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb Has Been Planted.
        /// </summary>
        public static string BombHasBeenPlanted {
            get {
                return ResourceManager.GetString("BombHasBeenPlanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness:.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Picker.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So that CSHUE can know what is going on in your CS:GO, a specific .cfg file must exist in the game&apos;s cfg folder, a gamestate_integration_cshue.cfg.
        ///
        ///If the bellow button is pressed, CSHUE will automatically try to find where CS:GO is installed in your machine, creating then the required file. Doesn&apos;t matter where you installed it, my precious application is going to find it MUAHAHA... Ahem... Here&apos;s the button:.
        /// </summary>
        public static string ConfigText {
            get {
                return ResourceManager.GetString("ConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the Hub. Please try again..
        /// </summary>
        public static string CouldNotConnect {
            get {
                return ResourceManager.GetString("CouldNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Terrorists Win.
        /// </summary>
        public static string CounterTerroristsWin {
            get {
                return ResourceManager.GetString("CounterTerroristsWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .cfg.
        /// </summary>
        public static string CreateCfg {
            get {
                return ResourceManager.GetString("CreateCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO process checking period:.
        /// </summary>
        public static string CsgoCheckingPeriod {
            get {
                return ResourceManager.GetString("CsgoCheckingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO GSI.
        /// </summary>
        public static string CSGOGSI {
            get {
                return ResourceManager.GetString("CSGOGSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t expect much finantial return from this application, but who knows, right? Donations are always appreciated.
        ///
        ///I&apos;m linking to a PayPal donation page. You will be able to donate from 1 to 9,999,999.99 dolars, any higher than this, please, email me a time and place and we meet there. You will also be able to choose &quot;Make this a monthly donation&quot; if you want to, well, make this a monthly donation..
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        public static string DonationCountry {
            get {
                return ResourceManager.GetString("DonationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string DonationCurrency {
            get {
                return ResourceManager.GetString("DonationCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSHUE%20donation.
        /// </summary>
        public static string DonationDescription {
            get {
                return ResourceManager.GetString("DonationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the above url in a browser.
        ///The url is composed of:
        ///	my PayPal email: joao7yt@gmail.com
        ///	a purpose description: CSHUE Donation
        ///	a country code: US
        ///	a currency code: USD.
        /// </summary>
        public static string DonationDetails {
            get {
                return ResourceManager.GetString("DonationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;
        ///business=joao7yt@gmail.com&amp;lc=US&amp;
        ///item_name=CSHUE%20Donation&amp;currency_code=USD&amp;
        ///bn=PP%2dDonationsBF.
        /// </summary>
        public static string DonationLink {
            get {
                return ResourceManager.GetString("DonationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File created at.
        /// </summary>
        public static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO cfg Folder Selection.
        /// </summary>
        public static string FolderSelection {
            get {
                return ResourceManager.GetString("FolderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow me.
        /// </summary>
        public static string FollowMe {
            get {
                return ResourceManager.GetString("FollowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Time.
        /// </summary>
        public static string FreezeTime {
            get {
                return ResourceManager.GetString("FreezeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub Selector.
        /// </summary>
        public static string HubSelector {
            get {
                return ResourceManager.GetString("HubSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Options.
        /// </summary>
        public static string LaunchOptions {
            get {
                return ResourceManager.GetString("LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string LightOff {
            get {
                return ResourceManager.GetString("LightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Selector.
        /// </summary>
        public static string LightSelector {
            get {
                return ResourceManager.GetString("LightSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights states.
        /// </summary>
        public static string LightsStates {
            get {
                return ResourceManager.GetString("LightsStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize CSHUE when CS:GO is detected.
        /// </summary>
        public static string MinimizeDetected {
            get {
                return ResourceManager.GetString("MinimizeDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to system tray.
        /// </summary>
        public static string MinimizeSystemTray {
            get {
                return ResourceManager.GetString("MinimizeSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version, &quot;{0}&quot;, is available..
        /// </summary>
        public static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lights found..
        /// </summary>
        public static string NoLightsFound {
            get {
                return ResourceManager.GetString("NoLightsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Gets Flashed.
        /// </summary>
        public static string PlayerGetsFlashed {
            get {
                return ResourceManager.GetString("PlayerGetsFlashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Gets a Kill.
        /// </summary>
        public static string PlayerGetsKill {
            get {
                return ResourceManager.GetString("PlayerGetsKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Gets Killed.
        /// </summary>
        public static string PlayerGetsKilled {
            get {
                return ResourceManager.GetString("PlayerGetsKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview lights while changing events settings.
        /// </summary>
        public static string PreviewLights {
            get {
                return ResourceManager.GetString("PreviewLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarternary.
        /// </summary>
        public static string Quarternary {
            get {
                return ResourceManager.GetString("Quarternary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember lights states.
        /// </summary>
        public static string RememberLights {
            get {
                return ResourceManager.GetString("RememberLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Starts.
        /// </summary>
        public static string RoundStarts {
            get {
                return ResourceManager.GetString("RoundStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run CS:GO.
        /// </summary>
        public static string RunCsgo {
            get {
                return ResourceManager.GetString("RunCsgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run CS:GO on CSHUE startup.
        /// </summary>
        public static string RunCsgoOnStartup {
            get {
                return ResourceManager.GetString("RunCsgoOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run minimized.
        /// </summary>
        public static string RunMinimized {
            get {
                return ResourceManager.GetString("RunMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run CSHUE when my computer starts.
        /// </summary>
        public static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string SecondsAbbreviation {
            get {
                return ResourceManager.GetString("SecondsAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the CS:GO cfg folder manually..
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Steam folder manually..
        /// </summary>
        public static string SelectSteamFolder {
            get {
                return ResourceManager.GetString("SelectSteamFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in browser.
        /// </summary>
        public static string ShowInBrowser {
            get {
                return ResourceManager.GetString("ShowInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show system tray icon.
        /// </summary>
        public static string ShowSystemTrayIcon {
            get {
                return ResourceManager.GetString("ShowSystemTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorists Win.
        /// </summary>
        public static string TerroristsWin {
            get {
                return ResourceManager.GetString("TerroristsWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary.
        /// </summary>
        public static string Tertiary {
            get {
                return ResourceManager.GetString("Tertiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also trigger player events when spectating.
        /// </summary>
        public static string TriggerSpectating {
            get {
                return ResourceManager.GetString("TriggerSpectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable.
        /// </summary>
        public static string Unreachable {
            get {
                return ResourceManager.GetString("Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use its color from {0} event.
        /// </summary>
        public static string UseMainEventColor {
            get {
                return ResourceManager.GetString("UseMainEventColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmup.
        /// </summary>
        public static string Warmup {
            get {
                return ResourceManager.GetString("Warmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find CS:GO path..
        /// </summary>
        public static string WarningCSGO {
            get {
                return ResourceManager.GetString("WarningCSGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find CS:GO Game State Integration file..
        /// </summary>
        public static string WarningGSI {
            get {
                return ResourceManager.GetString("WarningGSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS:GO Game State Integration file is corrupted..
        /// </summary>
        public static string WarningGSICorrupted {
            get {
                return ResourceManager.GetString("WarningGSICorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Hub is no longer reachable.
        ///Make sure the Hub is connected to the same network as yours and retry..
        /// </summary>
        public static string WarningHubNotAvailable {
            get {
                return ResourceManager.GetString("WarningHubNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the link button on your Hub..
        /// </summary>
        public static string WarningLink {
            get {
                return ResourceManager.GetString("WarningLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hub found.
        ///Make sure the Hub is connected to the same network as yours and retry..
        /// </summary>
        public static string WarningNoHub {
            get {
                return ResourceManager.GetString("WarningNoHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reachable Hubs found.
        ///Make sure the Hub is connected to the same network as yours and retry..
        /// </summary>
        public static string WarningNoReachableHubs {
            get {
                return ResourceManager.GetString("WarningNoReachableHubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hub connection..
        /// </summary>
        public static string WarningNotConnected {
            get {
                return ResourceManager.GetString("WarningNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Hubs..
        /// </summary>
        public static string WarningSearching {
            get {
                return ResourceManager.GetString("WarningSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find Steam path..
        /// </summary>
        public static string WarningSteam {
            get {
                return ResourceManager.GetString("WarningSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Hub..
        /// </summary>
        public static string WarningValidating {
            get {
                return ResourceManager.GetString("WarningValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
